# Generated by Django 2.2.5 on 2019-09-14 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190914_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 14, 23, 37, 27, 233334)),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
