version: "3.2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/src/frontend/
      - ./frontend/node-modules:/src/frontend/node_modules
    depends_on:
      - musicapp
    ports:
      - "3000:3000"
    command: npm start
  musicapp:
    build: ./backend
    volumes:
      - ./backend:/src/
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"