# Generated by Django 2.2.5 on 2019-09-18 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190914_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 5, 13, 29, 728257, tzinfo=utc), null=True),
        ),
    ]
